name: react-native-android-build-apk
on:
  push:
    branches:
      - feature/github-action-docker

jobs:
  build-android-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pnstack/codespace/react-native:latest
      options: --user root
    defaults:
      run:
        working-directory: /
    steps:
      - uses: actions/checkout@v3

      - name: pwd
        run: pwd

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Ls
        run: cd __w && ls -la

      - name: Build Android Release
        run: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
